services:
  haejo-dl:
    image: haejo
    container_name: haejo
    build:
      context: .
      args:
        USER_NAME: appuser
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ~/deeplearning-repo-4:/workspace
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_DEBUG_PLUGINS=1
      - QT_QPA_PLATFORM=xcb
      - QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins
      - QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID

    # getting all gpus
    privileged: true
    # communication between containers and host
    network_mode: host
    pid: host
    ipc: host
    
    # avoid exit
    tty: true
    stdin_open: true
    restart: always