services:
  haejo-dl:
    image: haejo
    container_name: haejo
    build:
      context: .
      args:
        USER_NAME: appuser
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ~/deeplearning-repo-4:/workspace
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITSHM=1
    # getting all gpus
    privileged: true
    # communication between containers and host
    network_mode: host
    pid: host
    ipc: host
    # using gpu
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia  # if count of device_ids not given, all gpus used
            capabilities: [gpu]
    
    # avoid exit
    tty: true
    stdin_open: true
    restart: always